# required line: specify the version of the docker-compose 
version: '3'

# services usually = container
services: 
  client:
    image: "yingtingyu33/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "yingtingyu33/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "yingtingyu33/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    # the server always restart if error occurs
    image: "yingtingyu33/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'